### ISSUE TITLE
-databasein flag not functional

### ISSUE THREAD

**Issue by rediaz111** [glycojones/privateer#31]
README states you can use -databasein flag to point to the privateer_glycomics_database.json file. 

If you pass the -databasein flag first, the program fails to run. If you pass the argument after -pdbin and -mtzin, the program will not crash but still does not recognize -databasein as a valid flag.

**Comment by GABRAH** [comment]
Dear Roberto, 

Apologies for this issue, which is definitely caused by me not maintaining README appropriately. "-databasein" flag at some point was replaced with "-glycomics_dbpath".

Nevertheless, Privateer should be able to find the "privateer_glycomics_database.json" on its own through environment variables if the "ccp4.envsetup-sh" is sourced. Therefore, ideally there should be no need for "-glycomics_dbpath" argument, and all that is required in terms of flags is the following: "-pdbin <filepath>", "-mtzin <filepath>" and "-glytoucan"

**Comment by rediaz111** [comment]
Hi Gabrah, thanks for the quick response!

Unfortunately, after I source "ccp4.envsetup-sh" then try to run privateer, the program fails to run unless the glycomics database is in /current_dir/data/glycomics.

Below is the output from running ccp4.envsetup-sh and the output from privateer when I try to run without a glycomics database in a subdir within the working dir.
`privateer_src
CCP4_MASTER = /home/rediaz/test/5fjj
CCP4 = /home/rediaz/test/5fjj/dependencies
If CCP4 variable above looks like: /home/user/privateer/build/executable/dependencies, rather than /home/user/privateer/dependencies:
then please try to source the ccp4.envsetup-sh script in root directory of the project, i.e. /home/user/privateer
by typing 'source ccp4.envsetup-sh'
`

`
pwd
/home/rediaz/test/5fjj/

/home/rediaz/privateer/build/executable/privateer -pdbin /home/rediaz/privateer/tests/test_data/5fjj.pdb -mtzin /home/rediaz/privateer/tests/test_data/5fjj.mtz -glytoucan -all_permutations

<B><FONT COLOR='#FF0000'>
<html> 
<hr>
<pre>
 
 ###############################################################
 ###############################################################
 ###############################################################
 ### CCP4 7.1: Privateer               version MKIV : 06/02/21##
 ###############################################################
 User: rediaz  Run date: 13/ 4/2022 Run time: 10:34:49 


 Please reference: Collaborative Computational Project, Number 4. 2011.
 "Overview of the CCP4 suite and current developments". Acta Cryst. D67, 235-242.
 as well as any specific reference in the program write-up.

</FONT></B>

Privateer version MKIV. Copyright 2013-2021 Jon Agirre (@glycojones) & University of York.
Contributors: Haroldas Bagdonas (@GABRAHREX) and the rest of Glycojones Team at York.
Please reference these articles: 

   - 'Privateer: software for the conformational validation of carbohydrate structures'
      Agirre et al, 2015 Nat Struct & Mol Biol 22(11):833-834.

   - 'Leveraging glycomics data in glycoprotein 3D structure validation with Privateer'
      Bagdonas, Ungar & Agirre, 2020 Beilstein Journal of Organic Chemistry 16(1):2523-2533.

Supplied arguments: 
pdbin 	/home/rediaz/privateer/tests/test_data/5fjj.pdb
mtzin 	/home/rediaz/privateer/tests/test_data/5fjj.mtz
glytoucan
all_permutations

THREADING: Privateer will use 256 of the 256 available threads...

Reading /home/rediaz/privateer/tests/test_data/5fjj.pdb... done.

 Spacegroup/cell information is missing from the PDB file.
 Privateer will still run, but may miss any important contacts described by crystallographic symmetry.

Reading /home/rediaz/test/5fjj/data/glycomics/privateer_glycomics_database.json for Glycomics database
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file: /home/rediaz/test/5fjj/data/glycomics/privateer_glycomics_database.json
`

**Comment by GABRAH** [comment]
Hello, 

judging from the logs that you shared, it appears that you might have sourced "ccp4.envsetup-sh" in the wrong directory. Sourcing of ccp4.envsetup-sh has to occur specifically in privateer's directory( /home/rediaz/privateer/ in your case ), because the environment variables rely on bash's PWD, rather than the file location. Admittedly, this behaviour should be changed and this has given me enough push to do so in near future. 

```
cd /home/rediaz/privateer
source privateerpython/bin/activate
source ccp4.envsetup-sh
cd /home/rediaz/test/5fjj/
/home/rediaz/privateer/build/executable/./privateer -pdbin /home/rediaz/privateer/tests/test_data/5fjj.pdb -mtzin /home/rediaz/privateer/tests/test_data/5fjj.mtz -glytoucan -all_permutations
```

should then make work Privateer as advertised.

Properly sourced ccp4.envsetup.sh, should then be able to automatically find "privateer_glycomics_database.json" in the following path: 
/home/rediaz/privateer/data/glycomics/privateer_glycomics_database.json
